= XBELmark XSLT
:nofooter:

== Web Browser

To dynamically transform an XBEL file into XHTML5 by a web browser, add the
following processing instruction before the `xbel` element:

----
<?xml-stylesheet type="text/xsl" href="/share/xbelmark/stylesheet/firefox/xhtml5.xsl"?>
----

where the URL to the XSL stylesheet should be appropriately adjusted. When an
XBEL file is served by an HTTP server, the web browser applies the XSL
stylesheet to it and displays its XHTML5 transform as a web page.

== Xalan

To build the XSLT extensions for Apache Xalan,

----
mvn package
----

The packaged JAR file contains the XSLT processor by Apache Xalan. To execute
an XSL transformation on an XBEL file,

----
java -jar target/xbelmark-0.1.0-jar-with-dependencies.jar \
  -XSL ../share/stylesheet/firefox/xhtml5.xsl \
  -IN /path/to/xbel.xml
----

== xsltproc

libxml2 and libxslt are required. libxml2 and libxslt are assumed to be at
standard locations. If not, their header and library directories can be
exported to `CPATH` and `LIBRARY_PATH`, respectively. To build the XSLT
extensions for xsltproc,

----
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=${HOME}/.local/opt/xbelmark ..
make install
----

To execute an XSL transformation on an XBEL file,

----
./target/bin/xbelmark ../share/stylesheet/firefox/xhtml5.xsl /path/to/xbel.xml
----

For help on the options accepted by XBELmark XSLT,

----
./target/bin/xbelmark --help
----
